version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
        - ./backend:/src
    ports:
      - "8000:8000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    network_mode: bridge
  db:
    build: ./db
    ports:
      - "13300:3306"