version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
        - ./backend:/app
    ports:
      - "8000:8000"
    network_mode: bridge
  redis:
    image: "redis:alpine"