version: '3'
services:

  backend:
    build: .
    depends_on: 
      - db
    environment:
      NODE_ENV: 'development'
      SERVER_PORT: 8000
      API_VERSION: 'v1'
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    network_mode: bridge

  db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_DATABASE: 'todo'
    ports:
      - "13300:3306"
    network_mode: bridge