version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
        - .:/src
    ports:
      - "8000:8000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    network_mode: bridge
  db:
    build: ./database
    ports:
      - "13300:3306"